main: net.lighttz.plugins.Main
name: LSystem
version: 1.0.0
author: ILighttz#0002
commands:
  kits:
    aliases: [kit]
  g:
    aliases: [global]
  anunciar:
    description: Anunciar sua loja vip
    permission: anunciar.re
  tell:
    aliases: [r]
  tpa:
    description: enviar tpa
  tphere:
    permission: tphere.re
  tp:
    permission: tp.re
  clearchat:
   permission: clearchat.re
  chat:
    permission: chatoff.re
  toggle:
    description: tira funções
  punir:
    permission: punir.re
  s:
    aliases: [staff]
    permission: staffchat.re
    permission-message: §cVocê não tem permissão para isso!